### ISSUE TITLE
Review Request

### ISSUE THREAD

**Issue by Sajeelzafar** [Sajeelzafar/JavaScript-Capstone#21]
We are a team of two people, [Sajeel Zafar](https://github.com/Sajeelzafar) and [Selma Hamutenya](https://github.com/SelmaNdapanda), and we have removed the tasks for the student C from our project list.
The link to our project is [here](https://github.com/Sajeelzafar/JavaScript-Capstone/projects/1).
The student A is Selma Hamutenya and student B is Sajeel Zafar.

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- Descriptive info ✔️ 

## Required Changes ♻️
- [ ] Kindly make sure to assign all tasks to at least one team member each as per this [requirement](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/setup_kanban_board.md#:~:text=Each%20of%20the%20team%20members%20should%20assign%20themselves%20to%20the%20correct%20cards.%20Decide%20who%20will%20be%20the%20assignee%20for%20the%20cards%20marked%20as%20group%20tasks.%20All%20cards%20on%20your%20Kanban%20board%20should%20have%20assignees).

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Sajeelzafar** [comment]
Thank you very much for your feedback. We have assigned the respective tasks to corresponding team mates.

**Comment by HAMMAS-SALEEM** [comment]
# Status: Approved :green_circle: :1st_place_medal: :100:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

## Hey @Sajeelzafar, @SelmaNdapanda :wave:

Great work on implementing the requsted changes. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

:heavy_check_mark: Following Requirements
:heavy_check_mark: Following Github Flow
:heavy_check_mark: Descriptive PR Title
:heavy_check_mark: Descriptive PR Summary
:heavy_check_mark: Following Linters

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

### Optional Changes

- [ ] It would be nice if you add your team member names in this Review Request issue summary above. and you can tell which student is student 1 and which student is student 2 :blush: for more details
